language: java

addons:
  apt:
    packages:
      - ant

jdk:
  - openjdk8

script: >
  cd ant-project && ant checkstyle
  && cd ../gradle-project && ./gradlew clean check --debug --stacktrace
  && rm -rf ~/.m2/repository/com/github/sevntu-checkstyle/sevntu-checks
  && cd ../maven-project && mvn checkstyle:check
  && rm -rf ~/.m2/repository/com/github/sevntu-checkstyle/sevntu-checks
  && cd ../maven-project && mvn checkstyle:check -Pgithub-maven-repo

sudo: false

cache:
  directories:
  - ~/.m2
  - ~/.gradle
  - ~/.ivy2

branches:
  only:
    - master

matrix:
  fast_finish: true
