version: 2.1

jobs:

  validate-with-maven-script:
    resource_class: small
    parameters:
      image-name:
        type: string
        default: "cimg/openjdk:11.0.18"
        description: "docker image to use"
      command:
        description: "command to run"
        type: string
        default: ""
    docker:
      - image: << parameters.image-name >>
    steps:
      - checkout
      - run: sudo apt update && sudo apt install -y ant
      - restore_cache:
          name: Restore Maven repo cache
          keys:
            - mvn-cache-{{ checksum "maven-project/pom.xml" }}
      - run:
          command: << parameters.command >>
      - run: ./.ci/validation.sh git-diff
      - save_cache:
          name: Save Maven repo cache
          key: mvn-cache-{{ checksum "maven-project/pom.xml" }}
          paths:
            - .m2

workflows:

  test:
    jobs:
      - validate-with-maven-script:
          name: "build-ant-project"
          command: "./.ci/validation.sh build-ant-project"
      - validate-with-maven-script:
          name: "build-gradle-project"
          command: "./.ci/validation.sh build-gradle-project"
      - validate-with-maven-script:
          name: "build-maven-project"
          command: "./.ci/validation.sh build-maven-project"
      - validate-with-maven-script:
          name: "build-maven-ant-project"
          command: "./.ci/validation.sh build-maven-ant-project"
